name: CI
on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build release DLL
        run: dotnet pack -c Release

      - uses: actions/upload-artifact@v2
        with:
          name: Impostor.Http.dll
          path: Impostor.Http/bin/Release/net6.0/Impostor.Http.dll

      - uses: actions/upload-artifact@v2
        with:
          name: Impostor.Http.nupkg
          path: Impostor.Http/bin/Release/Impostor.Http.*.nupkg

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: Impostor.Http/bin/Release/net6.0/Impostor.Http.dll
